name: Build UEDumper
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure my build for x64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build
        run: msbuild
